# Database configurations
database:
  host: 'localhost'
  name: ''
  username: ''
  password: ''

# HTTP basic authentication configurations, used for the API
authentication:
  username: ''
  password: ''
  
# OpenTok configurations
opentok:
  api_key: ''
  api_secret: ''
  
# Urban Airship configurations
urbanairship:
  is_production: false # Whether or not the app is in production
  development: # Information for the development app on Urban Airship
    app_key: ''
    app_secret: ''
    master_secret: ''
  production: # Information for the production app on Urban Airship
    app_key: ''
    app_secret: ''
    master_secret: ''
    
# Salt for short IDs
short_id_salt: ''

# Salt for sensitive data sent back and forth between the server and the app
# This exact same slat must also be entered in the configurations in the app
security_salt: ''

# URL to redirect to when visiting root
redirect_root: 'http://bemyeyes.org'


mandrill:
  api_key: ''
  from_email: ''
  from_name: ''
  reply_to: ''